### ISSUE TITLE
Sorry if this isn't the right place ...

### ISSUE THREAD

**Issue by ArchieLinux** [tahoma2d/tahoma2d.github.io#14]
... am a bit disoriented by the various Tahoma2D locations throughout the web.

On my Linux (Arch/EndeavorOS/i3wm) set ups (on multiple platform hardware), I have no problem running the Tahoma2D AppImage labeled as "Official Release" [v1.4.1 - 2024-02-01T00:07:47Z]. 

However, I've tried repeatedly by following the same download/extract steps on the downloaded Nightlys (on different nights) and keep getting this  immediate error message: 

![Screenshot-Tahoma-1 4-Load](https://github.com/tahoma2d/tahoma2d.github.io/assets/119451251/86a8a6ea-47dd-4d36-b1e1-5e1447e0b402)
 (Critical 1.4.1.  Undefined or empty "")

I'd give you more info, but the program never even opens beyond this so I have no trace or debug data to share.

This error is appearing on Dell, MacBookPro 2011, iMac 2019, all of which are running Arch Linux.

Since I'm following the same steps for both the Official Release and the Nightly(s), the former works and latter does not, I'm assuming there's either something about the nightly files or there's some configuration step I'm missing.

Any thoughts welcomed!

**Comment by manongjohn** [comment]
Please recreate this in https://github.com/tahoma2d/tahoma2d/issues
